version: '3.9'

networks:
  app_net:
    driver: bridge

volumes:
  backend_data:
    driver: local

services:
  backend:
    container_name: mlops-backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - PORT=5001
      - DATABASE_URL=sqlite:///rf_predictions.db
    volumes:
      - backend_data:/app/backend
    networks:
      - app_net
    ports:
      - "5001:5001"

  frontend:
    container_name: mlops-frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
    environment:
      - PORT=5000
      - DB_SERVICE_URL=http://backend:5001
    depends_on:
      - backend
    networks:
      - app_net
    ports:
      - "5000:5000"


